summit_xl:
  joint_blw_velocity_controller:
#    type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_brw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_frw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_front_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_flw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_front_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_front_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_front_pan
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
  joint_front_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_front_tilt
    pid: {p: 100.0, i: 0.01, d: 50.0}

  joint_rear_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_rear_pan
    pid: {p: 100.0, i: 0.01, d: 50.0}
    
  joint_rear_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_camera_rear_tilt
    pid: {p: 100.0, i: 0.01, d: 50.0}


  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
